---
# tasks file for eks_deploy
- name: Install kubectl
  become: yes
  ansible.builtin.shell: |
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
    rm kubectl
  args:
    creates: /usr/local/bin/kubectl

- name: Update kubeconfig for EKS
  ansible.builtin.shell: |
    aws eks update-kubeconfig --region us-east-1 --name flask-app-cluster
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
    AWS_REGION: "us-east-1"

- name: Create Kubernetes Secret
  ansible.builtin.shell: |
    kubectl create secret generic capstone-secret --from-literal=CAPSTONE_TEST={{ capstone_test }} --dry-run=client -o yaml | kubectl apply -f -

- name: Deploy to EKS
  ansible.builtin.shell: |
    kubectl apply -f {{ deployment_yaml_path }}
