---
# tasks file for eks_deploy
- name: Install kubectl
  become: yes
  ansible.builtin.shell: |
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
    rm kubectl
  args:
    creates: /usr/local/bin/kubectl

- name: Update kubeconfig for EKS
  ansible.builtin.shell: |
    aws eks update-kubeconfig --region us-east-1 --name flask-app-cluster --kubeconfig /tmp/kubeconfig
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
    AWS_REGION: "us-east-1"
    KUBECONFIG: "/tmp/kubeconfig"

- name: Debug kubeconfig file
  ansible.builtin.shell: cat /tmp/kubeconfig
  register: kubeconfig_content
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
    AWS_REGION: "us-east-1"
    KUBECONFIG: "/tmp/kubeconfig"

- name: Show kubeconfig content
  ansible.builtin.debug:
    var: kubeconfig_content.stdout

- name: Test kubectl connectivity
  ansible.builtin.shell: kubectl cluster-info
  register: kubectl_cluster_info
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
    AWS_REGION: "us-east-1"
    KUBECONFIG: "/tmp/kubeconfig"
  ignore_errors: true

- name: Show kubectl cluster-info output
  ansible.builtin.debug:
    var: kubectl_cluster_info.stdout

- name: Create Kubernetes Secret
  ansible.builtin.shell: |
    kubectl create secret generic capstone-secret --from-literal=CAPSTONE_TEST={{ capstone_test }} --dry-run=client -o yaml | kubectl apply --validate=false -f -
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
    AWS_REGION: "us-east-1"
    KUBECONFIG: "/tmp/kubeconfig"

- name: Deploy to EKS
  ansible.builtin.shell: |
    kubectl apply -f {{ deployment_yaml_path }}
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
    AWS_REGION: "us-east-1"
    KUBECONFIG: "/tmp/kubeconfig"
